version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "1337:80"   # HTTP (will redirect to HTTPS)
      - "1338:443"  # HTTPS with HTTP/2
    depends_on:
      - nextjs
    networks:
      - app_network  

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: 